### ISSUE TITLE
Installation of scheil

### ISSUE THREAD

**Issue by jayagreav** [pycalphad/scheil#2]
I tried to install scheil (pycalphad) as mentioned in github page but I alwayan get package not found error. please help me to fix it

**Comment by bocklund** [comment]
We're still in an early phase of development and scheil is actually not released via PyPI or Anaconda. Currently the only way to install is to install the development version. I updated the installation instructions to reflect this: https://github.com/pycalphad/scheil#installation

**Comment by jayagreav** [comment]
Thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bocklund** [comment]
The `scheil` package is now available via

(preferred) `conda install scheil` 

or `pip install scheil`
